name: Continuous Integration

on:
  pull_request:
    branches: [develop]

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        python-version: ['3.12']

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          channels: conda-forge
          channel-priority: strict
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          conda activate test
          conda install --yes -c conda-forge python=${{ matrix.python-version }}
          conda install --yes -c conda-forge matplotlib-base pyyaml openblas c-compiler h5py scipy spglib symfc cmake pytest-regressions pytest codecov pytest-cov pandas

      - name: Install phonopy and phono3py
        run: |
          conda activate test
          mkdir install_phonopy && cd install_phonopy  # to avoid phonopy directory as recognized as module path by pytest
          git clone https://github.com/phonopy/phonopy.git
          cd phonopy
          pip install -e . -vvv
          cd ..
          git clone https://github.com/phonopy/phono3py.git
          cd phono3py
          pip install -e . -vvv
          cd ..
          cd ..

      - name: Run pytest
        run: |
          conda activate test
          pytest -sv tests
